[build]
  command = "npm run build"
  publish = "out"

[forms]
  [forms.contact]
    name = "contact"
    fields = [
      { name = "firstName", type = "text", required = true },
      { name = "name", type = "text", required = true },
      { name = "email", type = "email", required = true },
      { name = "discord", type = "text", required = false },
      { name = "subject", type = "text", required = true },
      { name = "message", type = "text", required = true }
    ]
    
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 